spring:
    config:
      activate:
        on-profile: local
    datasource:
     url: "jdbc:mysql://localhost:3306/inflearn"
     username: "root"
     password: "root"
     driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: "jdbc:mysql://localhost:3306/inflearn"
    username: "root"
    password: "Am@zon11_!!@"
    driver-class-name: com.mysql.cj.jdbc.Driver